name: build_cyb

on:
  push:
    branches:
      - main

jobs:
  build_app:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.14.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Set environment variable with commit SHA
        run: |
          echo "COMMIT_SHA=${{ github.sha }}" >> $GITHUB_ENV

      - name: Install dependencies
        run: |
          cd ./front
          yarn install

      - name: Build app
        run: |
          cd ./front
          yarn install

      - name: Verify build directory
        run: |
          -ls -la
          echo "Contents of front directory:"
          ls -al front
          echo "Contents of dist directory (if exists):"
          ls -al front/dist || echo "dist directory does not exist"

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.ACTIONS_DEPLOY_ACCESS_TOKEN }}
          BRANCH: build
          FOLDER: ./front/dist
          CLEAN: true
